### ISSUE TITLE
提问！

### ISSUE THREAD

**Issue by anghunk** [heropoo/elegant-comment#1]
html应该写点啥注明一下呗
还有
这个代码是只能给自己查看吗
还是属于第三方的评论插件
每个进入博客的人都可以评论

**Comment by heropoo** [comment]
对的，这个项目是打算做一个第三方的评论插件。最近工作忙，一直搁置着，使用说明我后面有空了完善一下。

**Comment by metadetron** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @Awesomnonymous, @Daniel266, @imolable, @foxytanuki, @fpcMotif, @asebesta, @Chenyufeng-finn
